# Generated by Django 5.2.11 on 2026-02-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp32', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
