# Generated by Django 5.2.11 on 2026-02-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp32', '0002_commandhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led_name', models.CharField()),
                ('led_status', models.CharField()),
            ],
        ),
    ]
